# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "tailscale-fly-ams"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "41641"

[[services]]
  protocol = "udp"
  internal_port = 41641

  [[services.ports]]
    port = 41641
